INSERT INTO gift_certificate(id,name,description,price,duration) VALUES (1,'test 1', 'description 1', 1.0, 1);
INSERT INTO gift_certificate (id,name,description,price,duration) VALUES (2,'test 2', 'description 2', 2.0, 2);
INSERT INTO gift_certificate (id,name,description,price,duration)VALUES (3,'test 3', 'description 3', 3.0, 3);
INSERT INTO gift_certificate (id,name,description,price,duration)VALUES (4,'test 4', 'description 4', 4.0, 4);
INSERT INTO gift_certificate (id,name,description,price,duration)VALUES (5,'test 5', 'description 5', 5.0, 5);
INSERT INTO tag VALUES (1,'test tag 1');
INSERT INTO tag VALUES (2,'test tag 2');
INSERT INTO tag VALUES (3,'test tag 3');
INSERT INTO tag_certificate VALUES (1,1);
INSERT INTO tag_certificate VALUES (1,2);
INSERT INTO tag_certificate VALUES (2,2);
INSERT INTO tag_certificate  VALUES (2,3);
INSERT INTO tag_certificate  VALUES (3,1);